services:
  inventorysystemapi:
    image: inventorysystemapi
    build:
      context: .
      dockerfile: src/InventorySystem.Api/Dockerfile
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inventorysystemdb
    ports:
      - "3306:3306"
